export const CST = {
  SCENES: {
    LOAD: "LOAD",
    MAIN: "MAIN",
    GAME: "GAME"
  },
  IMAGES: {
    LOGO: "LOGO",
    BACKGROUND: "BACKGROUND"
  },
  SPRITES: {
    GLOBE: "GLOBE",
    BEAM : "BEAM",
    BLUECOVID19: "BLUECOVID19",
    GREENCOVID19: "GREENCOVID19",
    REDCOVID19: "REDCOVID19",
    PLAYER:"PLAYER",
    COVID19_EXPLOSION: "COVID19_EXPLOSION",
    POWERUPS  : "POWERUPS"
  },
  ANIMATIONS: {
    EARTH_ANIM: "EARTH_ANIM",
    BEAM_ANIM: "BEAM_ANIM",
    BLUECOVID19_ANIM: "BLUECOVID19_ANIM",
    GREENCOVID19_ANIM: "GREENCOVID19_ANIM",
    REDCOVID19_ANIM: "REDCOVID19_ANIM",
    PLAYER_ANIM: "PLAYER_ANIM",
    COVID19_EXPLOSION_ANIM: "COVID19_EXPLOSION_ANIM",
    LIFEPOWERUP_ANIM: "LIFEPOWERUP_ANIM",
    BEAM1POWERUP_ANIM : "BEAM1POWERUP_ANIM",
    BEAM2POWERUP_ANIM : "BEAM2POWERUP_ANIM",
    DESTROYALLCURRENTPOWERUP_ANIM : "DESTROYALLCURRENTPOWERUP_ANIM",
    FINISHLVLPOWERUP_ANIM : "FINISHLVLPOWERUP_ANIM",
    SHIELD1POWERUP_ANIM : "SHIELD1POWERUP_ANIM",
    SHIELD2POWERUP_ANIM : "SHIELD2POWERUP_ANIM",
    SCORE1POWERUP_ANIM : "SCORE1POWERUP_ANIM",
    SCORE2POWERUP_ANIM : "SCORE2POWERUP_ANIM",
    REPLICAPOWERUP_ANIM : "REPLICAPOWERUP_ANIM",
  },
  WINDOW: {
    ISMOBILE: navigator.userAgent.indexOf("Mobile") != -1
  }
};
