export const CST = {
  SCENES: {
    LOAD: "LOAD",
    MAIN: "MAIN",
    GAME: "GAME"
  },
  IMAGES: {
    LOGO: "LOGO",
    BACKGROUND: "BACKGROUND",
  },
  SPRITES: {
    GLOBE: "GLOBE",
    BLUECOVID19: "BLUECOVID19",
    GREENCOVID19: "GREENCOVID19",
    REDCOVID19: "REDCOVID19",
    PLAYER:"PLAYER",
    COVID19_EXPLOSION: "COVID19_EXPLOSION"
  },
  ANIMATIONS: {
    EARTH_ANIM: "EARTH_ANIM",
    BLUECOVID19_ANIM: "BLUECOVID19_ANIM",
    GREENCOVID19_ANIM: "GREENCOVID19_ANIM",
    REDCOVID19_ANIM: "REDCOVID19_ANIM",
    PLAYER_ANIM: "PLAYER_ANIM",
    COVID19_EXPLOSION_ANIM: "COVID19_EXPLOSION_ANIM"
  },
  WINDOW: {
    ISMOBILE: navigator.userAgent.indexOf("Mobile") != -1
  }
};
